[package]
name = "arc-live-release-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "arc-live-release-tool"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
zeroize.workspace = true
